tool
extends Node

#sync signals
signal sync_timer_timeout
signal sync_slider_moved
signal physics_state_changed
signal physics_reset_button_pressed
signal physics_rewind_to_cell
signal new_sync_cell_reached


#transition signals
signal level_select_menu_button_pressed
signal credits_button_pressed
signal settings_button_pressed
signal quit_button_pressed
signal back_button_pressed
signal level_select_button_pressed
signal pause_button_pressed
signal level_lose
signal level_win
signal resume_button_pressed
signal restart_button_pressed
signal next_level_button_pressed


signal open_scene
signal reload_current_scene
signal close_scene

#audio signals
signal volume_changed
signal mute_changed
